enchanting_table:
    custom_gui: true
    level_fifty: true
    lapis_in_table: true
    reset_on_reload: true
anvil:
    custom_gui: true
    level_divisor: 4
    default_use: false
    max_repair_level: 60
    damage: true
grindstone:
    custom_gui: true
    use_legacy: false
    take_enchantments: false
    set_repair_cost: true
    destroy_take_item: true
max_enchantments: 0
update_legacy_enchantments: false
use_enchanted_books: false
disable_enchant_method: 'visible'
enchantment_check: 300
drop_items_naturally: true
language: 'en_us'
language_file: 'language.yml'
villager_trades: false
use_comments: true
protection_conflicts: true
lore_on_top: true
version:
    get_latest: true
    get_experimental: false
wiki:
    on_login: true
    on_timer: false
    timer_seconds: 14400
    url: 'https://bit.ly/2N54NzC'
loots:
    mobs:
        use: true
        bookshelves: 0
        levels: 0
        treasure: false
    fishing:
        use: true 
        bookshelves: 0
        levels: 0
        treasure: true
    chests:
        use: true
        end_city_treasure: 
            bookshelves: 15
            levels: 3
            treasure: true
        simple_dungeon: 
            bookshelves: 0
            levels: 0
            treasure: true
        shipwreck_supply: 
            bookshelves: 0
            levels: 0
            treasure: true
        woodland_mansion: 
            bookshelves: 10
            levels: 1
            treasure: true
        stronghold_library: 
            bookshelves: 10
            levels: 1
            treasure: true
        stronghold_crossing: 
            bookshelves: 10
            levels: 1
            treasure: true
        stronghold_corridor: 
            bookshelves: 10
            levels: 1
            treasure: true
        underwater_ruin_big: 
            bookshelves: 0
            levels: 0
            treasure: true
        underwater_ruin_small: 
            bookshelves: 0
            levels: 0
            treasure: true
        pillager_outpost: 
            bookshelves: 10
            levels: 1
            treasure: true

gametype: 'survival'

config_comments: 

    enchanting_table: 
        custom_gui: 
        - 'Whether to use the custom enchanting table gui'
        - 'This will always be true if level_fifty is true'

        level_fifty: 
        - 'Whether to use the level fifty system of enchantments'
        
        lapis_in_table: 
        - 'If players need to insert lapis into the custom table for it to work'
        
        reset_on_reload: 
        - 'Resets enchantments in enchanting table whenever the server is reloaded'
        - 'Setting this to false means the only ways to reset enchantments are through /esreset and enchanting an item'
    anvil: 
        custom_gui: 
        - 'Whether to use the custom anvil gui'
        
        level_divisor: 
        - 'Greater numbers allow more anvil uses.'

        max_repair_level: 
        - 'The highest repair level that will be allowed in the anvil'
        - 'Only used when enchanting type is enhanced. '

        default_use: 
        - 'Allow default use of anvil GUI via option at bottom right of custom GUI.'
        - 'Only used when enchanting type is enhanced.'
        - 'Should only be true if anvil is used for custom recipes.'

        damage: 
        - 'The anvil will be damaged while using it - normal vanilla behavior on true'

    grindstone: 
        custom_gui: 
        - 'Whether to use the custom grindstone gui'
        - 'Will always use the custom gui in 1.13.2 and below'
        
        use_legacy: 
        - 'Whether to use the custom grindstone gui in 1.13.2 and earlier'
        - 'Will always be false above 1.13.2'
        
        take_enchantments: 
        - 'Use the grindstone to add enchantments from items to books.'
        - 'Only used when enchanting type is enhanced.'

        set_repair_cost: 
        - 'When grindstone takes enchantments, set repair cost of the generated book to the item used''s repair cost'

        destroy_take_item: 
        - 'When grindstone takes enchantments, destroy the item used'

    max_enchantments: 
    - 'Max enchantments on each item. 0 allows infinite'

    update_legacy_enchantments: 
    - 'Update any enchantments generated in EnchantmentSolutionLegacy'

    use_enchanted_books: 
    - 'Uses the vanilla Enchanted Books rather than Books to store enchantments.'

    disable_enchant_method: 
    - 'How disabling an enchantment in enchantments.yml or enchantments_advanced.yml will work.'
    - 'Options:'
    - 'vanish - removes enchantment from items'
    - 'visible - keeps enchantment on item, but custom effects will not work and anvil will remove enchant'
    - 'repairable - same as above but anvil will not remove enchant'

    enchantment_check: 
    - 'The number (in seconds) of time the plugin will run checks for other plugins ruining enchantments on items'
    - 'Will check 10 players a tick while running'
    - 'Lower numbers may cause more lag on the server'

    drop_items_naturally: 
    - 'Items will drop in the default Minecraft way rather than drop straight to the ground'
    - 'May cause issues with items flying away'

    language_file: 
    - 'The yml language file'

    language: 
    - 'The default language of the language file'

    villager_trades: 
    - 'Allow custom and/or high level enchants to appear in villager trades'

    use_comments: 
    - 'Show helpful comments in the config files'

    protection_conflicts: 
    - 'All protection types conflict with each other'

    lore_on_top: 
    - 'Custom enchantment lore will always be at the top of the lore'

    version: 
        get_latest: 
        - 'Check github for plugin releases (available on github and spigot)'

        get_experimental: 
        - 'Check github for plugin experimental versions (available only on github)'

    wiki: 
        on_login: 
        - 'Shows the wikipedia page to the user on login'

        on_timer: 
        - 'Shows the wikipedia page to the user on a timer'

        timer_seconds: 
        - 'The number of seconds between when users should be alerted to the wiki'

        url: 
        - 'The URL to the wiki - the default is the normal EnchantmentSolution wiki'

    loots: 
        mobs: 
            use: 
            - 'Allow custom and/or high level enchantments to spawn on mobs'
            bookshelves: 
            - 'Modify types of enchantments generated by setting the minimum amount of bookshelves'

            levels: 
            - 'Modify types of enchantments generated by setting the minimum lapis level'

            treasure: 
            - 'Whether the enchantments generated from this format should contain treasure enchantments'

        fishing: 
            use:
            - 'Allow custom and/or high level enchantments to appear while fishing'
            
            bookshelves: []

            levels: []

            treasure: []
        chests: 
            use:
            - 'Allow custom and/or high level enchants to spawn in chests'
            
    gametype: 
    - 'What does this option possibly mean? It seems to do nothing at the moment.'